### ISSUE TITLE
[New Feature] Music Command

### ISSUE THREAD

**Issue by sr229** [awau/owo-whats-this#10]
**TODO**
- [ ]  Simple Play and Pause Command
- [ ]  use ffmpeg instead of opus for cross-compatibility
- [ ] implement a skip/stop function (add voting system to it to promote fairness, Bot Owners should be exempted from this.)

**Comment by Ovyerus** [comment]
Coming in the refactor uwu

**Comment by sr229** [comment]
:eyes:

**Comment by sr229** [comment]
Closed because Milestone has been completed
